name: Publish
on:
  workflow_dispatch:
    inputs:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Detect version
        run: |
          export branch_name=${GITHUB_REF#refs/heads/}
          [[ "$branch_name" =~ ^release\/[0-9]+(\.[0-9]+)?$ ]] && export is_release=true || is_release=false
          [[ "$is_release" = 'true' ]] && export version="$(cat VERSION)" || version="$(cat VERSION)-${branch_name//\//-}"
          echo "IS_RELEASE=$is_release" >> $GITHUB_ENV
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
      - name: Build
        run: dotnet build -c Release src/cs/Prostoquasha.AmbientTransactions.nuget.slnf
      - name: Pack
        run: dotnet pack -c Release -p:PackageVersion="${{ env.VERSION }}" -p:PackageProjectUrl="https://github.com/Voronkov-A/prostoquasha.ambienttransactions" -p:Authors="Voronkov-A" src/cs/Prostoquasha.AmbientTransactions.nuget.slnf
      - name: Tag and release
        if: ${{ env.IS_RELEASE == 'true' }}
        uses: avakar/tag-and-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload nuget
        run: dotnet nuget push --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json src/cs/**/*.nupkg
